### ISSUE TITLE
Logging produces only garbage (binary data)

### ISSUE THREAD

**Issue by FransUrbo** [gauteh/defmt-serial#16]
I'm using [Embassy](https://github.com/embassy-rs/embassy/) for my [RPi/Pico project](https://github.com/FransUrbo/drive-by-wire/pull/1/files#diff-c37513afeac72746cef77ab72c170fd043bec66285cefb9e039f3e87629ad8f3).

I initialize the UART and do a write with it (using `blocking_write()`). Works fine, I get the "Hello World" just fine. But then when I initialize `defmt-serial`, all subsequent *defmt* functions just outputs garbage on the serial port.

I'm not a very experienced Rust developer, but I'm a fairly decent C/Python/Perl/PHP/etc developer, so I'm not a complete noob :).
Not entirely sure how `defmt-serial` actually works, I'm having trouble understanding the code, but it's almost like "something" is "garbaging" the buffer!

I've tried using UART0/PIN0, but same thing happens - but since the `blocking_write()` directly from the Embassy API works fine, I need to assume that *that* part at least works.. Which leads me to `defmt-serial`. However, I'm not experienced enough to find out what it is :(.

Any pointers would be most welcome..

<img width="488" alt="Screenshot 2024-06-07 at 08 17 49" src="https://github.com/gauteh/defmt-serial/assets/572706/ae9f1709-f23f-433f-9682-567bb0e1ea2c">

**Comment by FransUrbo** [comment]
Embassy do seem to have a [blocking::serial::Write](https://github.com/embassy-rs/embassy/blob/main/embassy-rp/src/uart/mod.rs#L993-L1003), although it uses `embedded_hal_02` instead of `embedded_hal`.

I've been trying to understand #14, which seems to be about just that - newer HAL.. ? However, that PR isn't finished, it fails to compile..

**Comment by gauteh** [comment]
Hi. That looks correct: You have to decode the output with `defmt-print`: https://github.com/gauteh/defmt-serial?tab=readme-ov-file#parsing-logs , there are examples for how to set that up with `cargo run` or Makefiles (https://github.com/gauteh/sfy/blob/main/sfy-buoy/Makefile#L37) . 

The PR isn't compiling because the HAL in one of the examples is on eh pre 1. I think I will just disable that example in CI.

**Comment by FransUrbo** [comment]
Oh!?? A note about that would be helpful :). That that's necessary I mean.

However, I did try that (`(stty speed 115200 >/dev/null && cat) </dev/cu.usbmodem2102 | defmt-print -e target.elf`), but didn't get anything. Turns out, that the `stty` doesn't work that way on MacOS - the port must be opened _before_ you set the speed!

But now I tried again (`cat < /dev/cu.usbmodem2102 | defmt-print -e target.elf`), then set the speed in a different terminal (`stty -f /dev/cu.usbmodem2102 speed 115200 -crtscts -mdmbuf`) and now it works!!

If you could update the documentation about this, I'd appreciate it.

**Comment by FransUrbo** [comment]
One note though, is there a reason why `defmt-print` is necessary? Could this not just output it in text directly?

**Comment by gauteh** [comment]
That's the whole point of defmt :) It sends encoded minimal data and you decode it on the host. This is explained in defmt docs. Otherwise you would just use normal logging to serial.

**Comment by FransUrbo** [comment]
"normal logging to serial"? As in, using the example in `example-std`?

**Comment by gauteh** [comment]
If you don't want encoded data, don't use defmt. Just print to serial.

**Comment by FransUrbo** [comment]
Ah. Well, `defmt` is quite nice, it takes care of a lot of the legwork :).

Thanx for the clarification!


For posterity, anyone else have problem with this on MacOS, this is a one-liner that works for me:
```shell
export DEV=/dev/cu.usbmodem2102 ; (cat < "${DEV}" & stty -f "${DEV}" speed 115200 -crtscts -mdmbuf) | defmt-print -e target.elf
```

As in, on MacOS, the `stty` needs to come _after_ the port have been opened! Otherwise, the OS will reset it to default (9600 baud etc).
